kitti360:
  data_root_dir: "/Datasets/KITTI-360/"
  data_poses_oxts_extract_dir: "data_poses_oxts_extract/"   # oxts 3003 imu
  data_2d_raw_dir: "data_2d_raw/"
  data_2d_raw_img_extension: ".png"
  data_3d_raw_dir: "data_3d_raw/"
  data_3d_raw_lidar_extension: ".bin"
  data_calibration_dir: "calibration/"
  data_poses_gt_dir: "data_poses/"
  sequence_number: "0010"

  topic_name_imu: "kitti360/data_imu_raw/data_imu_raw"
  topic_name_left_perspective: "kitti360/data_2d_raw/left_perspective"
  topic_name_right_perspective: "kitti360/data_2d_raw/right_perspective"
  topic_name_lidar_velo: "kitti360/data_3d_raw/lidar_velo"
  topic_name_gt_path: "kitti360/data_poses/gt_path"
  topic_name_gt_odom: "kitti360/data_poses/gt_odom"

  data_output_dir: "output/"